name: Print latest tag 1

on:
  workflow_dispatch:
  push:

jobs:
  print-latest-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: oprypin/find-latest-tag@v1
        with:
          repository: jerrinfrancis/gha-tests
          releases-only: true
        id: latest_tag

      - name: Print latest tag
        run: echo "Latest release tag is ${{ steps.latest_tag.outputs.tag }}"
